arquivo = open('/Users/mhirleylopes/PycharmProjects/GeekUniversity/leitura_de_arquivos/teste')
ret = arquivo.read().split('\n')
print(ret[1])
print('- ' * 15)
arquivo1 = open('/Users/mhirleylopes/PycharmProjects/GeekUniversity/leitura_de_arquivos/teste')
arquivo1.seek(0)
print(arquivo1.read(65))
arquivo1.seek(0)
# print(arquivo1.readline())
print('- ' * 15)
rets = arquivo1.readlines()
print(len(rets))
arquivo.close()
print(arquivo1.closed)
arquivo1.close()
print(arquivo1.closed)
